-- Migration 002: campaign_members
-- Tracks every player who has joined a campaign via the server-generated playerId.
-- This table is the authoritative source for whether a playerId is legitimate for a campaign.
-- Append-only: do not edit this file after it has been applied to any environment.

CREATE TABLE IF NOT EXISTS campaign_members (
  campaign_id TEXT NOT NULL,
  player_id   TEXT NOT NULL,
  joined_at   TEXT NOT NULL,
  PRIMARY KEY (player_id),
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_campaign_members_campaign
  ON campaign_members (campaign_id);
