name: Terraform CI

on:
  pull_request:
    paths:
      - "infra/terraform/**"
  push:
    branches:
      - main
    paths:
      - "infra/terraform/**"

permissions:
  id-token: write   # required for OIDC (GitHub → AWS)
  contents: read

env:
  TF_WORKING_DIR: infra/terraform/envs/dev

jobs:
  terraform:
    name: Terraform fmt / validate / plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Format check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false
